version: 0.0
os: linux
files:
  - source: codedeploy/upstart/codedeploy.conf
    destination: /etc/init/
  - source: /
    destination: /home/ec2-user/goc/src/github.com/hoohawa/golang_web
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  # ApplicationStop:
  #   - location: codedeploy/application_stop.sh
  #     timeout: 300
  #     runas: root
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: codedeploy/application_start.sh
      timeout: 300
  # ValidateService:
  #   - location: codedeploy/validate_service.sh
  #     timeout: 10
  #     runas: root